name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:

concurrency:
  # Concurrency group that uses the workflow name and PR number if available
  # or commit SHA as a fallback. If a new build is triggered under that
  # concurrency group while a previous build is running it will be canceled.
  # Repeated pushes to a PR will cancel all previous builds, while multiple
  # merges to main will not cancel.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment (PR)  
        if: ${{ github.event_name == 'pull_request' }}  
        shell: bash  
        run: |  
          echo "LAST_COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> ${GITHUB_ENV}  
      - name: Setup Environment (Push)  
        if: ${{ github.event_name == 'push' }}  
        shell: bash  
        run: |  
          echo "LAST_COMMIT_SHA=${GITHUB_SHA}" >> ${GITHUB_ENV}
      - name: Set build tag
        shell: bash
        run: |
          echo "BUILD_TAG=${LAST_COMMIT_SHA:0:7}" >> $GITHUB_ENV
      - name: Checkout main repo 'dev'
        uses: actions/checkout@v3
        with:
          repository: 'SeedSigner/seedsigner'
          ref: dev
          submodules: true
        # run: |
        #   git clone -b dev --recurse-submodules https://github.com/SeedSigner/seedsigner.git
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          sudo apt-get install libzbar0
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r tests/requirements.txt -r l10n/requirements-l10n.txt
          pip install -e .
      - name: Generate current 'dev' screenshots
        run: |
          mkdir -p artifacts/dev
          python -m pytest tests/screenshot_generator/generator.py
          mv ./seedsigner-screenshots/* ./artifacts/dev/
      # - name: Wipe out the translations submodule
      #   run: |
      #     cd seedsigner
      #     git submodule deinit -f -- src/seedsigner/resources/seedsigner-translations
      #     rm -rf .git/modules/src/seedsigner/resources/seedsigner-translations
      #     git rm -f src/seedsigner/resources/seedsigner-translations
      #     rm -rf src/seedsigner/resources/seedsigner-translations
      - name: Checkout updated translations
        # uses: actions/checkout@v3
        # with:
        #   path: src/seedsigner/resources/seedsigner-translations
        #   # ref: ${{ github.sha }}
        run: |
          rm -rf src/seedsigner/resources/seedsigner-translations
          git clone https://github.com/${{ github.repository}}.git src/seedsigner/resources/seedsigner-translations
          cd src/seedsigner/resources/seedsigner-translations
          git checkout $BUILD_TAG
          git status
      - name: Compile updated translations catalogs
        run: |
          python setup.py compile_catalog
          cd src/seedsigner/resources/seedsigner-translations
          git status
      - name: Generate latest screenshots
        run: |
          rm -rf seedsigner-screenshots
          mkdir -p artifacts/latest
          python -m pytest tests/screenshot_generator/generator.py
          mv ./seedsigner-screenshots/* ./artifacts/latest/
      - name: Diff screenshots
        run: |
          mkdir -p artifacts/diff
          python src/seedsigner/resources/seedsigner-translations/.github/diff_screenshots.py ./artifacts/dev ./artifacts/latest ./artifacts/diff
      # - name: Clean up artifacts
      #   run: |
      #     rm -rf ./artifacts/latest
      #     rm -rf ./artifacts/dev
      - name: Archive CI Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ci-artifacts
          path: artifacts/**
          retention-days: 7
        # Upload also when tests fail. The workflow result (red/green) will
        # be not effected by this.
        if: always()
